#!/usr/bin/env bash

## Declare variables:
PROGRAM=$(basename "$0")
OUT=$(yarn lint --max-warnings=0)
STATUS=$?
OUT_LENGTH=$(wc -l <<< "$OUT")

if [ $STATUS -eq 0 ]; then
  if [ $OUT_LENGTH == 4 ]; then
    echo "$PROGRAM: Passed lint check!"
  else
    echo "$PROGRAM: Some files were reformatted; please stage the ones you'd \
like to commit!"
    exit 1
  fi
else
	echo "$PROGRAM (error): $OUT"
	exit 2
fi
