version: "3.7"

services:
  resume:
    image: stevenxie/vue-resume:latest
    build:
      context: .
      cache_from:
        - stevenxie/vue-resume:latest
        - stevenxie/junior:latest
        - stevenxie/vue-resume:builder
        - node:10.11-alpine
      target: production
    container_name: resume
    ports:
      - "3000:80"
